services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: DB_HOST
        value: db.kszaocjurkxamnfpdukq.supabase.co
      - key: DB_NAME
        value: postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: wMMR$xrhLXL*!&5
      - key: DB_PORT
        value: "14474"
